export const products = [
  {
    id: 1,
    h1: "iWatch",
    h2: "A healthy leap ahead",
    link1: "Learn more >",
    link2: "Buy >",
    className: "iWatch",
    img: "https://www.apple.com/v/home/ay/images/promos/apple-watch-series-8/promo_apple_watch_series_8__ch7rexplmihe_large.jpg",
  },
  {
    id: 2,
    h1: "iPad",
    h2: "Lovable. Drawable. Magical",
    link1: "Learn more >",
    link2: "Buy >",
    className: "iPad",
    img: "https://www.apple.com/v/home/ay/images/promos/ipad/promo_ipad__fioegapg12qi_large.jpg",
  },
  {
    id: 3,
    h1: "MacBook Pro",
    h2: "Supercharged by M2 Pro and M2 Max",
    link1: "Learn more >",
    link2: "Buy >",
    className: "MacBookPro",
    img: "https://www.apple.com/v/home/ay/images/promos/macbook-pro-14-and-16/promo_mbp__ek7p477bkp6q_large.jpg",
  },
  {
    id: 4,
    h1: "HomePod",
    h2: "Profound sound.",
    link1: "Learn more >",
    link2: "Buy >",
    className: "HomePod",
    img: "https://www.apple.com/v/home/ay/images/promos/homepod/promo_homepod__f7jnolq94m2y_large.jpg",
  },
  {
    id: 5,
    h1: "AirPods Pro",
    h2: "Rebuilt from the sound up",
    link1: "Learn more >",
    link2: "Buy >",
    className: "AirPodsPro",
    img: "https://www.apple.com/v/home/ay/images/promos/airpods-pro/promo_airpods_pro_avail__gaxggskofx6y_large.jpg",
  },
  {
    id: 6,
    h1: "iCard",
    h2: "Get up to 3% Daily Cash back with every purchase",
    link1: "Learn more >",
    link2: "Buy >",
    className: "iCard",
    img: "https://www.apple.com/v/home/ay/images/promos/apple-card/tile__cauwwcyyn9hy_large.jpg",
  },
];
